### PR TITLE
Jiayin & Mengdie Project Update

### PR DESCRIPTION
**Pull request by mengdge**

### CODE REVIEW

**Comment by sjcjoosten** [comment]
Fei @jamesguo71 and Kyle @bensinkk will have to deal with parsing in a similar way to you, so perhaps you can share some of your implementation and coordinate (you can make pull-requests to each-other's code!).

**Comment by sjcjoosten** [comment]
I helped Fei and Kyle this morning with their parser, please reach out to them if you'd like to share the parser code. Their github https://github.com/bensinkk/cs30/ isn't yet updated with the code we wrote this morning but I'm confident they'll do that soon.
Alternatively, reach out to me if you'd like my help with the parser

**Comment by bensinkk** [comment]
> I helped Fei and Kyle this morning with their parser, please reach out to them if you'd like to share the parser code. Their github https://github.com/bensinkk/cs30/ isn't yet updated with the code we wrote this morning but I'm confident they'll do that soon.

Updated!

**Comment by mengdge** [comment]
> > I helped Fei and Kyle this morning with their parser, please reach out to them if you'd like to share the parser code. Their github https://github.com/bensinkk/cs30/ isn't yet updated with the code we wrote this morning but I'm confident they'll do that soon.
> 
> Updated!

FYI. Our github is https://github.com/JiayinHu97/cs30

**Comment by jamesguo71** [comment]
Hi @mengdge ,

Please note that I made a small correction to the parser so as to parse LaTex percentage sign properly (we missed dealing with the forward slash before % in LaTex). Will push to main in a short while. If you guys are using the parser, please update accordingly.

**Comment by bensinkk** [comment]
Making another small change to the parser, it currently applies mathematical operations in reverse order (i.e. addition before multiplication) so fixing that.

**Pull request merged**
